name: sign_and_autism
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5  # Ensure this is correctly formatted
  cupertino_icons: ^1.0.8
  collection: ^1.17.0
  image_picker: ^1.0.0
  get: ^4.7.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.5
  convex_bottom_bar: ^3.2.0
  crossword: ^1.3.2
  flutter_tts: ^4.2.2
  vibration: ^3.1.3
  google_sign_in: ^6.2.2
  image: ^4.5.3
  hive_ce: ^2.10.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/asl.tflite
    - assets/labels.txt
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/images/easy.jpg
    - assets/images/medium.jpg
    - assets/images/hard.jpg
    - assets/signs/
    - assets/images/piece3.png
#    - assets/images/cat_piece_1.jpg
#    - assets/images/cat_piece_2.jpg
#    - assets/images/cat_piece_3.jpg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
