// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe5x-zLHS1O1HfjNPw20LvSAjbSTLb90Q',
    appId: '1:629346765995:web:92a24ee0febafef718bbee',
    messagingSenderId: '629346765995',
    projectId: 'signlanguage-4519e',
    authDomain: 'signlanguage-4519e.firebaseapp.com',
    storageBucket: 'signlanguage-4519e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5MBz6PpLcN1rbPww1xsYbQAsJoRLRxc',
    appId: '1:629346765995:android:ae8b4fcfaec275e118bbee',
    messagingSenderId: '629346765995',
    projectId: 'signlanguage-4519e',
    storageBucket: 'signlanguage-4519e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDEPDxzlHuibcrqZy9pLxxYSFn5BV1sWU',
    appId: '1:629346765995:ios:c1c74d0b837bc42518bbee',
    messagingSenderId: '629346765995',
    projectId: 'signlanguage-4519e',
    storageBucket: 'signlanguage-4519e.firebasestorage.app',
    androidClientId: '629346765995-0sv4gl97kguf4r85t67qj1sq5vs9rmeg.apps.googleusercontent.com',
    iosClientId: '629346765995-oodojefe900tcgc7e83ghbrd1vl9edkk.apps.googleusercontent.com',
    iosBundleId: 'co.numl.signAndAutism',
  );

}